### ISSUE TITLE
Guidance on the version of ksops to use

### ISSUE THREAD

**Issue by ede-n** [viaduct-ai/kustomize-sops#114]
For a given version of ArgoCD, what is the recommended version of ksops to use?

In my specific case, 

ArgoCD version: 2.0.1
Kustomize version(suggested by ArogCD [here](https://github.com/argoproj/argo-cd/blob/v2.0.1/hack/tool-versions.sh>)): 3.9.4
ArgoCD Go Version([here](https://github.com/argoproj/argo-cd/blob/33eaf11e3abd8c761c726e815cbb4b6af7dcb030/go.mod#L3)):  1.16
Kustomize-sops Go Version current([here](https://github.com/viaduct-ai/kustomize-sops/blob/3fb3b41146240deeeba1c50aca495e3a9eb6a12c/go.mod#L3)): 1.14 

In the `README.md`, the example under [ksops-repo-sever-patch](https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch) has a comment `# Match Argo CD Go version`.

```
initContainers:
        - name: install-ksops
          # Match Argo CD Go version
          image: viaductoss/ksops:v2.5.5
          command: ["/bin/sh", "-c"]
```

1. Should I be choosing Kustomize-sops version [2.4.0 ](https://github.com/viaduct-ai/kustomize-sops/releases/tag/v2.4.0)?
2. What does the comment `# Match Argo CD Go version` mean? Given the latest ksops Go version is 1.14 and ArgoCd Go version is 1.16.

Appreciate your help.
