### ISSUE TITLE
override helm secret 

### ISSUE THREAD

**Issue by hroyg** [viaduct-ai/kustomize-sops#118]
Hi ,
We are using ksops with kustomize plugin for argocd , argocd application is pointing to the path the  secret i located and using a "generators"  stanza in the kustomization.yam  file we call the ksops plugin to decry-pt and create the secret.
in the same kustomization.yaml file we also have a "base" stanza that points to another argocd application that installs a Helm Chart  for us with helm3, this Chart is installing the same secret we already decrypted and deployed using ksops , we tried giving the secret the "replace/merge" annotation but ksops plugin is throwing an exception it cannot replace/merge secret that is not found, it seems as the generator stanza is running before the "base" directive that deploys the helm and the secret from helm and there for ksops canot replace/merge our encrypted secret.
is there anything we can do better to make work make the helm secret be rendered before the ksops generator and then it will be replaced ??

############################### kustomization.yaml  #####################################3 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

// The following line creates argocd application which deploys Helm
bases:
- https://github.com/ORGANIZATION/k8s-gitops-resources/infra/datadog?ref=main  

patchesStrategicMerge:
- overlay.application.yaml  

generators:
- secrets/secret-generator.yaml

**Comment by devstein** [comment]
Hi @hroyg thanks for making an issue! Can you please share the output of `kustomize version` and the exact error message?

At a glance, the only difference from the example `kustomization.yaml` you shared and the [example in the tests](https://github.com/viaduct-ai/kustomize-sops/blob/master/test/behaviors/kustomization.yaml) is the use of the deprecated `bases` key. Can you replace `bases` with `resources`? 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/ORGANIZATION/k8s-gitops-resources/infra/datadog?ref=main

patchesStrategicMerge:
- overlay.application.yaml

generators:
- secrets/secret-generator.yaml
```

Also, make sure to verify the namespaces of the secrets match. This is a common source of the "secret not found" error.
