### ISSUE TITLE
stringData merge not working

### ISSUE THREAD

**Issue by imranismail** [viaduct-ai/kustomize-sops#126]
- Exec plugin
- Plugin version v2.5.7
- Kustomize Version 3.10.0

```
.
├── base
│   ├── kustomization.yaml
│   ├── secret.enc.yaml          # no behavior, stringData: {key1: <encrypted>}
│   ├── sops.yaml
└── dev
    ├── kustomization.yaml
    ├── secret.enc.yaml          # behavior: merge, stringData: {key2: <encrypted>}
    └── sops.yaml
```

`$ kustomize build --enable_alpha_plugins dev`

Unexpected output:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  key2: <encrypted>
```

Expected output:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  key1: <encrypted>
  key2: <encrypted>
```
