### ISSUE TITLE
KSOPS v3.0.0 issue with ArgoCD v2.1.1

### ISSUE THREAD

**Issue by shuker85** [viaduct-ai/kustomize-sops#133]
![image (1)](https://user-images.githubusercontent.com/50396675/131638491-8c78db33-a294-447c-b402-c1a888d5c0a5.png)

Downgrade to v.2.6.0 fixed the problem for us.

**Comment by devstein** [comment]
Hi @shuker85 thanks for making an issue. The error is coming from `kustomize` not `KSOPS`, so it's interesting that downgrading fixed it. To help me debug, can you share more information about your setup?

1. How are you integrating KSOPS + Argo CD? (Custom Docker build, repo server patch, helm w/ custom tooling) 
2. Can you provide an example manifest(s) with that represents the kustomize functionality you are using? For example, the error message indicates you may be using the `namePrefix:` transformer. 
3. Are you able to reproduce the error locally w// KSOPS v3.0.0?

**Comment by devstein** [comment]
For context, [this is where the error is thrown](https://github.com/kubernetes-sigs/kustomize/blob/28707bf5dfe795e9656628115c629b073f0addb1/api/internal/utils/makeResIds.go#L39-L48)

**Comment by shuker85** [comment]
Hi, we're using the repo server patch approach with initiContainers and we do have `nameSuffix` present

```
nameSuffix: -dev
namespace: api
bases:
  - ../base
commonLabels:
  app: api-dev
images:
  - name: api
    newName: ghcr.io/xxxx/api:v0.0.1
patchesStrategicMerge:
  - cm.yaml
```
