### ISSUE TITLE
Trouble decrypting file

### ISSUE THREAD

**Issue by dalekurt** [viaduct-ai/kustomize-sops#135]
## Version
Argo CD `v2.1.2`
kustomizs-sops `{Version:v4.3.0+ksops.v3.0.1 GitCommit:v4@v4.3.0 BuildDate:2021-09-01T20:13:35Z GoOs:linux GoArch:amd64`

## What I've done so far

I have a AWS EKS cluster with permissions to KMS decrypt. SOPS config is using the KMS key to encrypt locally on my machine, commit and push to git. 

_.sops.yaml_
```
---
creation_rules:
  - encrypted_regex: '^(data|stringData)$'
    kms: "redacted"
```

Using a custom Argo CD container image with the kustomize-sops

_Custom Dockerfile_
```
ARG ARGO_CD_VERSION="v2.1.2"
ARG KSOPS_VERSION="v3.0.1"

FROM viaductoss/ksops:$KSOPS_VERSION as ksops-builder

FROM argoproj/argocd:$ARGO_CD_VERSION


# Switch to root for the ability to perform install
USER root

# Set the kustomize home directory
ENV XDG_CONFIG_HOME=$HOME/.config
ENV KUSTOMIZE_PLUGIN_PATH=$XDG_CONFIG_HOME/kustomize/plugin/

ARG PKG_NAME=ksops

# Override the default kustomize executable with the Go built version
COPY --from=ksops-builder /go/bin/kustomize /usr/local/bin/kustomize

# Copy the plugin to kustomize plugin path
COPY --from=ksops-builder /go/src/github.com/viaduct-ai/kustomize-sops/*  $KUSTOMIZE_PLUGIN_PATH/viaduct.ai/v1/${PKG_NAME}/

# Switch back to non-root user
USER argocd
```

The updated `argocd-cm` ConfigMap with the following:

```
data:
  kustomize.buildOptions: "--enable-alpha-plugins"
```

Additionally, the following files are in the repo (and path)

_kustomization.yaml_
```
generators:
  - ./secret-generator.yaml
 ```

_secret-generator.yaml_
```
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: demo-secret-generator
  namespace: demo
files:
  - ./secrets.yaml
```

_secrets.yaml_

```
redacted
```

## Issue

Executing `kustomize build ` from within the `argo-repo-server` Pod
```
kustomize build /tmp/redacted/demo --enable-alpha-plugins
trouble decrypting file Error getting data key: 0 successful groups required, got 0Error: failure in plugin configured via /tmp/kust-plugin-config-288993863; exit status 1: exit status 1
```
