### ISSUE TITLE
Using transformers with ksops

### ISSUE THREAD

**Issue by omer2500** [viaduct-ai/kustomize-sops#165]
Hi,

First let me say, This is a great tool!

i need the secret name with hash to be injected to a custom resource Rollout (argo-rollouts)
with a configmap i managed to pull this off with transformer nameReference config.
so anywhere i wrote the name of the configmap generator it will replace the value with the configmap name with the generated hash

i want to do the same with my secret generator of ksops is there any support for this? if yes what are my options?

my configuration:

```
nameReference:
  - kind: ConfigMap
    fieldSpecs:
      - kind: Rollout
        path: spec/template/spec/containers/envFrom/configMapRef/name
  - kind: Secret
    fieldSpecs:
      - kind: Rollout
        path: spec/template/spec/containers/envFrom/secretRef/name
```

and then on the kustomization file:

```
configurations:
 - ./kustomize-configuration.yaml
 ```
