### ISSUE TITLE
Secret merging of stringData vs data

### ISSUE THREAD

**Issue by alexknips** [viaduct-ai/kustomize-sops#166]
I might have found an issue with SOPS, kustomize or kustomize-sops. Unfortunately I don't know which tool is doing something wrong.

The issue.

Given a secret (decrypted)
```
apiVersion: v1
kind: Secret
metadata:
    name: demo-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    Secret1: ABC
data:
    Secret3: ABC
```

and an overlayed secret 

```
apiVersion: v1
kind: Secret
metadata:
    name: demo-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    Secret2: DEF
data:
    Secret4: DEF
```

that is merged 

the output of 
`kubectl kustomize --enable-alpha-plugins demo/overlays`

or `kustomize build --enable-alpha-plugins demo/overlays`

is 
```
apiVersion: v1
data:
  Secret3: ABC
  Secret4: DEF
kind: Secret
metadata:
  name: demo-secrets-924gtdkd22
stringData:
  Secret2: DEF
type: Opaque
```

and stringData is not merged in the same manner as data.

I have tried this also with the newest version of KSOPS
```
kustomize build --enable-alpha-plugins --enable-exec demo-secret-merging/overlays 
```

and the result is the same.

I attached my demo that one should extract into a folder `demo` to reproduce the issue.
[demo.tar.gz](https://github.com/viaduct-ai/kustomize-sops/files/10504458/demo.tar.gz)

Best regards
Alexander
