### ISSUE TITLE
Issue with argocd integration

### ISSUE THREAD

**Issue by AnthonyWC** [viaduct-ai/kustomize-sops#193]
I am using argo-cd integration according to doc with viaductoss/ksops:v4.2.1 but i have issue with decryption; if i re-create kustomization.yaml files on argocd-repo-server and manually run kustomize it works so i am baffled why it doesn't work with argocd.

```
argocd@argocd-repo-server-57f4469b7b-s7zs4:~$ argocd version
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

I am using GPG key from k8 secret; i imported gpg key in container command via
```
                gpg --import /sops-gpg/sops.asc &&
                gpg --list-key &&
                entrypoint.sh argocd-repo-server --redis argocd-redis:6379 --loglevel debug
```
where i mounted pgp secret and i see imported key listed.

:
```
argocd@argocd-repo-server-57f4469b7b-s7zs4:~$ gpg --list-keys
/home/argocd/.gnupg/pubring.kbx
-------------------------------
pub   rsa4096 2023-06-23 [SCEA]
      26BCC50767349385B6656762B0804DF66634080E
```

```
argocd@argocd-repo-server-57f4469b7b-s7zs4:~$ ls -la /usr/local/bin/k*
-rwxr-xr-x 1 root root 30840104 May 26 15:35 /usr/local/bin/ksops
-rwxr-xr-x 1 root root 27401720 May 26 15:36 /usr/local/bin/kustomize
```

```
cat << EOF > secret.yaml
apiVersion: v1
data:
  token: NEJEMUNFMjMtRTNDMC00QkJGLUE3NUUtQUJBMTAzRUU5NUM5
kind: Secret
metadata:
  name: app-secret
EOF
```
```
cat << EOF > .sops.yaml
creation_rules:
  - pgp: "26BCC50767349385B6656762B0804DF66634080E"
EOF
```

```
cat << EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml
EOF
```
```
cat << EOF > secret-generator.yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secret.yaml
EOF
```
sops --encrypt --in-place secret.yaml

file is encrypted with gpg:
```
argocd@argocd-repo-server-57f4469b7b-s7zs4:~/test$ head secret.yaml
apiVersion: ENC[AES256_GCM,data:mAM=,iv:mRn1QIHELRdKEGHMmuFGtkEMDEU+qAdxJlxiA2qTOyE=,tag:Fn3jC9x1OH4kx05KneITUA==,type:str]
data:
    token: ENC[AES256_GCM,data:4plLHBnsIrMVxntUA47kp7GrGfpJpofk4VlRDT3SWdWA53KudhSpGgOxLHBWMQT8,iv:HChdklSxbk5kFWGimu2dFXfNvii2Z6cIZ8eaW9dmQnA=,tag:vrqfVqyMcIDZ5qwNj71OVA==,type:str]
kind: ENC[AES256_GCM,data:uDVdhA32,iv:/baMnnz/x0wIX3Wx7FyaGkVqEYjm8356nRZ8RmLcd/Y=,tag:bg9owMMaiq7kYcIduTH7hA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lHa9oRGOD+AA1A==,iv:At7wPr8IUFzW2X4o0M58pwprjzqCqCHub5BbrsoH2DY=,tag:YYtwaUOVAvkyeRcXyumkYA==,type:str]
```

kustomize works as expected
```
argocd@argocd-repo-server-57f4469b7b-s7zs4:~/test$ kustomize build --enable-alpha-plugins --enable-exec .
apiVersion: v1
data:
  token: NEJEMUNFMjMtRTNDMC00QkJGLUE3NUUtQUJBMTAzRUU5NUM5
kind: Secret
metadata:
  name: app-secret
```

ksop-test2 directory contains same file and it works locally with kustomize build but fails in argocd:

```
argocd-repo-server-99bf848c4-wf2qx` argocd-repo-server time="2023-06-24T18:46:15Z" level=error 
msg="finished unary call with code Unknown" error="Manifest generation error (cached): `kustomize build 
.overlays/saas/testing3/deploy/ksop-test2 --enable-alpha-plugins --enable-exec` failed exit status 1: failed to 
evaluate function: error decrypting file \"secret.enc.yaml\" from manifest.Files: trouble decrypting file: Error getting 
data key: 0 successful groups required, got 0unable to generate manifests: error decrypting file \"secret.enc.yaml\" 
from manifest.Files: trouble decrypting file: Error getting data key: 0 successful groups required, got 0Error: 
couldn't execute function: exit status 1" grpc.code=Unknown grpc.method=GenerateManifest 
grpc.service=repository.RepoServerService grpc.start_time="2023-06-24T18:46:15Z" grpc.time_ms=125.063 
span.kind=server system=grpc
```

I had this as applicationset with git generator but i also tried manually creating it as app in GUI; both has issue decrypting file.
