### ISSUE TITLE
The Kubernetes API could not find viaduct.ai/ksops for requested resource. Make sure the "ksops" CRD is installed on the destination cluster.

### ISSUE THREAD

**Issue by adeel-ansari** [viaduct-ai/kustomize-sops#198]
I am having an issue with getting ksops to work with ArgoCD.  The error I'm seeing in ArgoCD is:

`The Kubernetes API could not find viaduct.ai/ksops for requested resource [ resource name ]. Make sure the "ksops" CRD is installed on the destination cluster.`

I am using viaductoss/ksops:v4.2.1 and followed the instructions to integrate with ArgoCD using the Helm chart modifications.

I have the following in my argocd-cm:

```
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: ""
  kustomize.buildOptions: --enable-alpha-plugins --enable-exec
```

When I exec into my argocd repo pod I see the files that need to be there:

```total 56880
-rwxr-xr-x 1 root root 30840104 May 26 15:35 ksops
-rwxr-xr-x 1 root root 27401720 May 26 15:36 kustomize
```

It seems like /usr/local/bin is part of the path.  Running kustomize version gives me:
`(devel)
`

Running ksops in the pod shows this:
```
KSOPS is a flexible kustomize plugin for SOPS encrypted resources.
KSOPS supports both legacy and KRM style exec kustomize functions.

kustomize Usage:
- kustomize build --enable-alpha-plugins --enable-exec

Standalone Usage :
- Legacy: ksops secret-generator.yaml
- KRM: cat secret-generator.yaml | ksops
```

Other information:
- kubectl version = 1.22.8
- Using Bitnami argocd chart

Let me know if you need any more information.

**Comment by johnl** [comment]
This seems like argo is trying to apply the generator yaml directly to kubernetes rather than kustomize using it to generate an actual secret which should then be applied.

Can you include your kustomization.yaml here?

**Comment by adeel-ansari** [comment]
Hi @johnl , thanks for looking into this.  I have just included my kustomization content at the bottom of the original message.  I was more or less following the examples given on the KSops github page.

Not to misguide what you're looking into, but I noticed that Bitnami has a different way of installing CRD's than the ArgoCD charts.  It's possible I haven't installed those correctly.  I think the KSops instructions are given using the ArgoCD helm chart not Bitnami.  Unfortunately I wasn't able to test with the ArgoCD chart because it needs a later version of Kubernetes and kubectl.

**Comment by kmazurek244** [comment]
Hi, I'm facing the same issue on Rancher with ArgoCD 3.1.4, deployed with argo-cd provided helm chart. 
I have added the ksops binary via init container (curl downloaded binary). 
I have in place: `kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"`

Env variables:
```   env:
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt
    - name: XDG_CONFIG_HOME
      value: /.config
```
And mounted volumes:
```
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /.config/sops/age/keys.txt
      name: sops-age
      subPath: keys.txt
```
kustomize.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta2
kind: kustomization
generators:
  # Reference the ksops plugin configuration
  - ksops-config.yaml
```

ksops-config.yaml
```
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-config
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
# List all SOPS-encrypted YAMLs that you want ksops to handle
  - one-secret.yaml
  - two-secret.yaml
  - three-secret.yaml
```
The output is:
The Kubernetes API could not find viaduct.ai/ksops for requested resource /ksops-config. Make sure the "ksops" CRD is installed on the destination **cluster.**
The Kubernetes API could not find kustomize.config.k8s.io/Kustomization for requested resource /. Make sure the "Kustomization" CRD is installed on the destination cluster.
