### ISSUE TITLE
KSOPS Config With Argo Values.yaml - Unable to find plugin root

### ISSUE THREAD

**Issue by TitanRob16** [viaduct-ai/kustomize-sops#207]
There seems to be some info missing from the README regarding the ksops installation via the values.yaml file. 

I have the following in my values.yaml file:

```
server:
...
  config:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
repoServer:
...
  volumes:
    - name: custom-tools
      emptyDir: {}
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.2.4
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
```

However, when I try to create an application via Argo CD's GUI, I get the error:

``
Unable to create application: application spec for gitops-argocd-sops is invalid: InvalidSpecError: Unable to generate manifests in base: rpc error: code = Unknown desc = `kustomize build <path to cached source>/base --enable-alpha-plugins --enable-exec` failed exit status 1: Error: loading generator plugins: failed to load generator: unable to find plugin root - tried: ('<no value>'; homed in $KUSTOMIZE_PLUGIN_HOME), ('/usr/local/bin/kustomize/plugin'; homed in $XDG_CONFIG_HOME), ('/home/argocd/.config/kustomize/plugin'; homed in default value of $XDG_CONFIG_HOME), ('/home/argocd/kustomize/plugin'; homed in home directory)
``

Some older blogs say to use a config like this instead:
```
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: install-ksops
          # Match Argo CD Go version
          image: viaductoss/ksops:v2.1.1-go-1.14
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              export PKG_NAME=ksops;
              mv ${PKG_NAME}.so /custom-tools/;
              mv $GOPATH/bin/kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      serviceAccountName: gke-argocd-demo
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
              # Verify this matches a XDG_CONFIG_HOME=/.config env variable
            - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
              name: custom-tools
              subPath: ksops.so
          # 4. Set the XDG_CONFIG_HOME env variable to allow kustomize to detect the plugin
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
```

But this also doesn't work. 

There's very clearly a problem with the plugin location; how should the values.yaml be configured?

**Comment by devstein** [comment]
Hey @TitanRob16 sorry that you are running into issues. Can you share your generator manifest? 

Given the error it looks like you're using the legacy style exec plugins, which like the blog suggests, requires `XDG_CONFIG_HOME` to be set. It'll look something like this (notice no `.so` after `ksops`)

```yaml
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
              # Verify this matches a XDG_CONFIG_HOME=/.config env variable
            - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
              name: custom-tools
              subPath: ksops
          # 4. Set the XDG_CONFIG_HOME env variable to allow kustomize to detect the plugin
          env:
            - name: XDG_CONFIG_HOME
              value: /.config

```
