### ISSUE TITLE
Replacing existing secrets with overlay causes issues

### ISSUE THREAD

**Issue by jetersen** [viaduct-ai/kustomize-sops#212]
I base a basic setup:
```
| base
  | kustomization.yaml
  | cloudflare-api-token.yaml
  | secrets-generator.yaml
| cluster1
  | kustomization.yaml
  | cluster-specific-secret.yaml
  | secrets-generator.yaml
| clsuter2
  | kustomization.yaml
  | secrets-generator.yaml
```

When applying secrets for cluster1 that uses base I get the following error:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `kustomize build <path to cached source>/staging --enable-alpha-plugins --enable-exec` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from '../base': '<path to cached source>/base' must resolve to a file': recursed accumulation of path '<path to cached source>/base': merging from generator &{0xc0003cef00 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"Secret", isClusterScoped:false}, Name:"cert-manager-cloudflare", Namespace:"cert-manager"} does not exist; cannot merge or replace
```

Fails in argocd but also locally 🤔

**Comment by jetersen** [comment]
@dosu-bot how does the behavior create compare to replace? What if the element already exists?

**Comment by jetersen** [comment]
A google search on "kustomize.config.k8s.io/behavior"

The readme links to https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md but this does not give insights into the behaviors that do exist 😓

**Comment by jetersen** [comment]
@dosubot how does the behavior create compare to replace? What if the element already exists?

**Comment by devstein** [comment]
Hey @jetersen the kustomize generator behaviors are poorly documented...I usually end up reading the kustomize code 🙁 

This issue doesn't have to do with KSOPS, but is a quirk of the order in which kustomize evaluates your manifests. Are you able to share any more information about your manifests files? Hard to debug without seeing the manifests

**Comment by jetersen** [comment]
The behavior I was looking for was upsert and remove any unknown values. It seems the default is merging.
I had a case with cert-manager-cloudflare having the key created manually with an `token` inside the secret data but ksops did not remove the unknown field.

`base/kustomization.yaml`
```
generators:
  - ./secrets-generator.yaml
```
`base/secrets-generator.yaml`
```
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./grafana.yaml
  - ./cloudflare-api-token.yaml
```
`cloudflare-api-token.yaml`
```
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cloudflare
    namespace: cert-manager
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    cloudflare_api_token: snip
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-28T19:11:00Z"
    mac: snip
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
    namespace: external-dns
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    cloudflare_api_token: snip
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-28T19:11:00Z"
    mac: snip
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
```
