### ISSUE TITLE
AWS KMS: How to handle aws_profile?

### ISSUE THREAD

**Issue by christoffer-eide** [viaduct-ai/kustomize-sops#219]
We have been using ksops for some time now. It works great, thanks for creating and maintaining this 💪

Our devs likes to create `.sops.yaml` config files with an `aws_profile`:
```
creation_rules:
  - encrypted_regex: ^(data|stringData)$
    kms: 'arn:aws:kms:eu-north-1:<arn>'
    aws_profile: my-aws-profile
```

When a secret is encrypted with `sops`, the`aws_profile` is added as metadata to the encrypted file:
```
apiVersion: v1
kind: Secret
metadata:
    name: my-secret
data:
    foo: ...
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:<arn>
          created_at: "2023-11-15T10:10:29Z"
          aws_profile: my-aws-profile
    version: 3.8.1
```
This makes it convenient for the devs to run `sops` and `kustomize build` locally, as the correct AWS profile is configured automatically.

We run a shared ArgoCD instance that is used by multiple teams. When we decrypt secrets there, it fails if the AWS SDK is unable to find the `aws_profile` specified in the sops metadata:
```
$ kustomize build --enable-alpha-plugins . > /dev/null 
unable to generate manifests: error decrypting file "my-secret.enc.yaml" from manifest.Files: trouble decrypting file: Error getting data key: 0 successful groups required, got 0Error: failure in plugin configured via /var/folders/y5/1lj9_kqn4ts3wb3r8xdgykwc0000gp/T/kust-plugin-config-505625821; exit status 1: exit status 1
```

Calling `sops` directly gives a more descriptive error:
```
$ sops -d my-secret.enc.yaml 
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  arn:aws:kms:eu-north-1:<arn>
    - | failed to decrypt sops data key with AWS KMS: operation
      | error KMS: Decrypt, failed to sign request: failed to
      | retrieve credentials: failed to refresh cached credentials,
      | no EC2 IMDS role found, operation error ec2imds:
      | GetMetadata, access disabled to EC2 IMDS via client option,
      | or "AWS_EC2_METADATA_DISABLED" environment variable

```

Our current workaround is to create a matching AWS profile in ArgoCD, which is a recurring PITA.

Looking at [kms/keysource.go](https://github.com/getsops/sops/blob/v3.8.1/kms/keysource.go#L309), it uses the `aws_profile` from the metadata when configuring the AWS SDK. There is no way to override this using env vars, unlike [gcpkms/keysource.go](https://github.com/getsops/sops/blob/v3.8.1/gcpkms/keysource.go#L240).

Is overriding the `aws_profile` something that can (or should) be supported in ksops?
