### ISSUE TITLE
 ksops + argocd  + helm - plugin doesn't seem to be active/run

### ISSUE THREAD

**Issue by conor-nsurely** [viaduct-ai/kustomize-sops#226]
Hi all,

I have installed Argocd using helm, with the helm values file used to configure the init container which installs ksops to Argocd .

I am using the helm values from [here ](https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#argo-cd-helm-chart-with-custom-tooling)

And all the values seem to be present in the configmap / deployments in the cluster.
    
I am using Argocd v2.9 and  viaductoss/ksops:v4.3.1


In the argo-repo-server logs I can see 
```
│ install-ksops Installing KSOPS...                                                                                                                                                                                                              │
│ install-ksops Done.
```

And if I start a shell on the argo-repo-server, "kustomize" and "ksops" are present on the path and seem to be installed correctly.

When I add an encrypted secret to Git, Argo fails to deploy saying
`one or more objects failed to apply, reason: Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 3 (retried 5 times).
`

It seems like the plugin is not running and Argocd is just trying to deploy the encrypted secret directly.

Where am I going wrong?

( I have tried $XDG_CONFIG_HOME = /.config also to no avail)

**Comment by devstein** [comment]
Hey @conor-nsurely thanks for making a detailed issue. At least we know that KSOPS is installed correctly.

1. Can you verify that [`kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
 `](https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#enable-kustomize-plugins-via-argo-cd-configmap) is set on the ArgoCD config map?

2. If it is, are you able to share more information about your K8s manifests and directory structure?

**Comment by conor-nsurely** [comment]
Hey @devstein 

1. It is enabled but I did notice there's also a flag disabling exec. Not sure where that has come from, maybe a default in Helm
```
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  kustomize.buildOptions: --enable-alpha-plugins --enable-exec
  server.rbac.log.enforce.enable: "false"
```

I've chaged `exec.enabled` to `true`, but there doesn't seem to be a difference.

---

2. Here's the secret that Argo is failing to apply

```
apiVersion: v1
data:
    cache_secret: ENC[AES256_GCM,data:d0Yg4P60Vi5AcwxlSJ/oPw==,iv:VwcckTKniflsOFzBLCzDDgbJB8W63MAknlrx52afaX8=,tag:oF3Xoj5aVFdR7D74UJO9yQ==,type:str]
kind: Secret
metadata:
    name: 123-secret
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dev/locations/global/keyRings/ksops-test/cryptoKeys/gke
          created_at: "2024-01-15T16:07:55Z"
          enc: CiQAR1OX8+1vLMju1VB94xq2gJkVki4eI6847X9NEXv3cHPMGRUSSQAFusxYIaFO2vNbWnaXrIx+u1xaH9LfQfxYqcwXtzrrU1h+rliLX6MWJuWfClj3g04JaA8iElW3EGy6Us5w/WvfRDfZfjEGHB0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-15T16:07:55Z"
    mac: ENC[AES256_GCM,data:Zr+bXPfbkq+lQAr9y9Ybue6Qqf+sNPE05hpnGtzF0tdUlnAWOVMFzCGzQZoZnqQlUxO/SQiPR1ncJxWy8ab4LDY5k8IoI+HygDK6dC1igXB+dJawTGGfRKhCtM5tOOlxIYG6rYRg43SlNKzNE7C6f4m90qW5xsDT+NSefG9jUn4=,iv:atOxnkFhkRU/8uGpTNi2YdcX/N/M7oynpTR0WogH7MA=,tag:ARnoyZVsXyVVncVSCqYswQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
```

I have the secret in a a top level directory by itself. I have put other yaml files in there as a sanity check and they all deploy just fine.

---

3. I assume I'm generating the secret incorrectly.

Do I need to apply anything else to kubernetes?`Like the KSOPS kustomize Generator from step 5 of the general instructions.

```apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: example-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
```

---



4. Is it possible to use Workflow Identity federation to retrieve the GCP key or does the key have to be passed via an environment variable? I assume there would be another error though if failing to decrypt was the sole issue.

Really appreciate the help!
