### ISSUE TITLE
Remote targets

### ISSUE THREAD

**Issue by zadjadr** [viaduct-ai/kustomize-sops#228]
I want to be able to use remote targets with ksops.

Something like this should work, but it seems that it does not:

```
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: my-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - https://gitlab.com/a/b/defaults//resources/secrets/secret.asc.yaml?ref=feat/abc
```

I would expect ksops to just use the kustomize feature: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md
