### ISSUE TITLE
Deployment Fails to Pull Image from AWS ECR Using KSOPS with Argo CD: No Basic Auth Credentials

### ISSUE THREAD

**Issue by LeoAnt02** [viaduct-ai/kustomize-sops#230]
Hello,

I'm experiencing an issue with deploying a Kubernetes application using Argo CD, where the deployment fails to pull an image from AWS ECR. The error indicates a lack of basic auth credentials, despite the secret being seemingly correctly set up via KSOPS.

Not sure if this is a bug, or I'm missing something 
Any idea ? 

#### Environment:
- **Argo CD Version**: 
v2.10.1+a79e0ea 
kustomize
v5.2.1 2023-10-19T20:13:51Z
Platform
linux/arm64
kubectl
v0.26.11

- **KSOPS Version**: 4.3.1

#### Issue Description:
When creating the image pull secret manually via the Kubernetes CLI, everything works as expected. However, when attempting to use KSOPS to manage the secret within Argo CD, the secret `pull-staging` does not appear to be present or correctly applied, leading to image pull failures.

#### Steps to Reproduce:
1. **Manual Secret Creation** (Works):

```
   kubectl create secret docker-registry pull-staging \                             
     --docker-server=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com \
     --docker-username=AWS \
     --docker-password=$(aws ecr get-login-password) \
     --namespace=staging

```

```
   kubectl get secret pull-staging -n staging          
   # Secret is found
```

And argoCD pod deploy successfully 

2. **Using KSOPS** (Fail):

pull-staging.dec.yml: 

looks like this

```
apiVersion: v1
kind: Secret
metadata:
    name: pull-staging
    namespace: staging
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ******
```

generator.yml:

```
     apiVersion: viaduct.ai/v1
     kind: ksops
     metadata:
       name: pull-staging
       namespace: staging
       labels:
         app: web
       annotations:
         config.kubernetes.io/function: |
           exec:
             path: ksops
     secretFrom:
     - metadata:
         name: pull-staging
         namespace: staging
         labels:
           app: web
         annotations:
           kustomize.config.k8s.io/needs-hash: "false"
       type: kubernetes.io/dockerconfigjson
       files:
       - secret/pull-staging.enc.yml

```

kustomization.yml:

```
     resources:
       - ../../base

     namespace: staging

     configMapGenerator:
       - name: config
         env: config.properties

     generators:
       - generator.yml

```

Deployment.yml 

```
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: web
     spec:
       replicas: 1
       template:
         spec:
           containers:
           - name: web
             image: ******.dkr.ecr.us-east-2.amazonaws.com/*****:latest
           imagePullSecrets:
           - name: pull-staging

```

### Error on argoCD pod : 
`    ERROR: Failed to pull image "*****.dkr.ecr.us-east-2.amazonaws.com/*****:latest": no basic auth credentials`

My argocd has been patched with this

```
# argo-cd-repo-server-ksops-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
        ## If you use AWS or GCP KMS, don't forget to include the necessary credentials to decrypt the secrets!
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: argocd-aws-credentials
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: argocd-aws-credentials
                  key: secretkey

``` 

and config map to enable the --enable-alpha-plugins --enable-exec

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

```

and my aws secret are present and created correctly

```
❯ kubectl get secret argocd-aws-credentials -n argocd 
NAME                     TYPE     DATA   AGE
argocd-aws-credentials   Opaque   2      21h
```
