### ISSUE TITLE
Create a Kubernetes Secret from an encrypted dotenv file results in stringData instead of data 

### ISSUE THREAD

**Issue by tomklapka** [viaduct-ai/kustomize-sops#260]
Create a Kubernetes Secret from an encrypted dotenv file ganerates a secret with `stringData` content e.g.:
```
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: xyz-secrets
      annotations:
        kustomize.config.k8s.io/behavior: merge
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
      - .secrets.enc.env
```
But Kustomize SecretGenerator generates secret with `data` content:
Also in Kustomize doc (https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/) is a following note: The **stringData field for a Secret does not work well with server-side apply.**

It makes sense to me keeping up with Kustomize.

`kustomize v5.3.0`
`kops v4.3.2`
