### ISSUE TITLE
secrets-generator file pattern?

### ISSUE THREAD

**Issue by jetersen** [viaduct-ai/kustomize-sops#276]
One improvement to the secrets generator would be to take a file pattern over a list of files.

```yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
filePatterns:
  - ./.*.sops.yaml
```

Which works together with how `.sops.yaml` config file works:
```yaml
creation_rules:
  - path_regex: .*.sops.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age: bob
```
