### ISSUE TITLE
Call out kustomize.config.k8s.io/behavior in documentation

### ISSUE THREAD

**Issue by daurnimator** [viaduct-ai/kustomize-sops#35]
Trying to figure out how to merge secrets, I discovered the kustomize annotation `kustomize.config.k8s.io/behavior`. Which can be used to merge secrets (e.g. if you want to add or override a secret field in an overlay)

```yaml
metadata:
    annotations:
        kustomize.config.k8s.io/behavior: merge
```

Upstream docs: https://github.com/kubernetes-sigs/kustomize/tree/b679e33d47e689c077dfec224aa9d2b59f8fda2f/docs/plugins#generator-options
Example usage with KSOPS: https://github.com/hashbang/gitops/blob/92d640f1421de9a41d96a4b78d85d0034af768d3/argocd/argo-cd-notifications-secret.enc.yaml#L6
