### ISSUE TITLE
AccumulateFile error during using gpg

### ISSUE THREAD

**Issue by majinghe** [viaduct-ai/kustomize-sops#85]
Hi team

I am trying to use gpg to encrypt the sensitive data in kustomize files, below is my file layout:
```
$ tree
.
└── application
    ├── base
    │   ├── deployment.yaml
    │   ├── ingress.yaml
    │   ├── kops-secret.yaml
    │   ├── kustomization.yaml
    │   ├── secret
    │   │   ├── secret.env.yaml
    │   │   ├── secret.registry.yaml
    │   │   └── secret.tls.yaml
    │   └── service.yaml
    └── overlays
        ├── dev
        ├── prod
        └── svt
            ├── configs
            │   └── env.txt
            ├── ingress.yaml
            ├── kustomization.yaml
            ├── replicas.yaml
```
Where `secret.env.yaml`,`secret.registry.yaml`,`secret.tls.yaml` are files encrypted with sops via gpg, below is my `.sops.yaml`:

```
creation_rules:
  - encrypted_regex: '^(data|username|password|.dockerconfigjson|user|pwd)$'
    pgp: '8F5D08B6669F3F4855B1568F2C60B7289BD33123'
```
For `secret.registry.yaml`, the context is :
```
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:WMMIzwbL1Mz524piX/l/ZIC1GmucQBsbrsQH5lBscGvMrlSQelWgQtBpwcM80EmVUttTcxauw+JR3gxDkICeBIQVKF4Ro3Cad89EuAdqQPZxycANGB+ZN31yr5v4Ljz+7ea09IZytWHASv0MImoWP1RtEqr1QjFIgKALP8FQUEuYLy9xYNJZrSBzzEs6oNE9n56lEw==,iv:7U/R+1gKDZXNZknkvnXmKRAYcNQOr1WJY+eZF/Gfk=,tag:DnpJwObaIhqRkrnchjVarw==,type:str]
kind: Secret
metadata:
    labels:
        app: application
    name: registry-secret
    namespace: application
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-04T08:22:23Z'
    mac: ENC[AES256_GCM,data:Wgpp7CkIKFqKUEg4FOZedohAnru5jxItxO86DeO7XKvhFC2qplBLcdVHcqEXeZoF0EEO0E9ustAn9nKkMtwQwTU0wKct3K+TKBxhPE8cvvq6QbMPkjC+F3DUXDhsH1MMq68bGG00o6G49ioXJBRz5YsMoYH6gBqxejOhcvTD3e8=,iv:1C/4m7jDDkH6zE3peKkN9wu0v2lAIgmi5RuDXdY0=,tag:rGrqNz14fL8pEh5FV5qvNA==,type:str]
    pgp:
    -   created_at: '2021-01-04T08:22:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA+bbBfsayC7dAQwAv1ed5/UXA8FgUzqaEQK5IMZHR2P/2X9LQH06mWhLfqE+
            +VUArvzvRQ74aX3KpH6lM5TrDa34Xex2qGG2Y8/Nlf0BQijSLAIdyyWLRPrN3esV
            ceUm53Je4uAOFhhkJKbGHL5lvG6KXVCMnLoVRVum+2jo5bnKHoUT4bUabHKhd3Ov
            MQwuxFnPw7ObIcjEspXT8bq6gkAk8Ykw21SMSViekynlArWcIX03Y0tb+oUJWCpX
            s7o+ewJ3IYE2SXjoRXfc6pszBpe8KglSWasMOwXj+uAu/33bOA2DKnLVmFVJJVm3
            LMcsOMxuqATQSO3vM0A3ZRguvbeP+0SaB9faJsR2XzH4XaAqD9CF50n0U3PgfNE
            S3zjO9k+AnsbMwPyDKVPbL3NwjqF55SFbPE3RyFmzWy53d3Rl/UgHMrzGAnBeRtz
            HzmWLNYcVmUw/NkHhBLYJuBqgvfovVduTk1QUYDTDYk9YLsoqNYlOVrJvqIlPwvj
            q1Kyc2KaaXpLAP+wcozk0l4BWWvBDxMe1a4iFlNi0p4as6tGa19KCv8/w4olYI/8
            jQVFylYyCYUzIJ0BW+zumrHMd58Jld/6W/EHdsizJHpRex1O1SvoHImTQR6s0GUd
            jUjz4mjX/tk3dhuT14
            =553i
            -----END PGP MESSAGE-----
        fp: 8F5D08B6669F3F4855B1568F2C60B7289BD33123
    encrypted_regex: ^(data|username|password|.dockerconfigjson|user|pwd)$
    version: 3.6.1
```
The `kustomize` version is :
```
$ kustomize version
{Version:v3.9.1+ksops.v2.3.2 GitCommit:v3@v3.9.1 BuildDate:2020-12-30T18:03:43Z GoOs:linux GoArch:amd64}
```
When i used ksops with Argocd, follow this instruction : https://github.com/viaduct-ai/kustomize-sops, i got the below error:
```
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../../base': '/tmp/git@github.com_k8sdevops_devops/kustomize/application/base' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/tmp/git@github.com_k8sdevops_devops/kustomize/application/base': trouble converting file 'secret/secret.registry.yaml' to a resource: trouble decrypting file secret/secret.registry.yaml: Error getting data key: 0 successful groups required, got 0"
```
I have already import  the gpg key into the `repo-server`:
```
$ gpg --list-keys
/home/argocd/.gnupg/pubring.kbx
-------------------------------
pub   rsa3072 2021-01-02 [SC] [expires: 2023-01-02]
      8F5D08B6669F3F4855B1568F2C60B7289BD33123
uid           [ unknown] my-name <my-mail>
sub   rsa3072 2021-01-02 [E] [expires: 2023-01-02]
```

I already configure the `repo-server` according to this : https://github.com/viaduct-ai/kustomize-sops/issues/24 ,I really do not know how to fix this? Cloud you please help to give some suggestion? Thanks very much.

**Comment by devstein** [comment]
Hi @majinghe thanks for making an issue! You are right that your issue is the same as #24 and there is an likely issue with your PGP setup. 

Did you follow the [PGP w/ KSOPS demo](https://github.com/james-callahan/example-gitops/blob/master/argocd/argo-cd-import-pgp-key.yaml) mentioned in [this comment](https://github.com/viaduct-ai/kustomize-sops/issues/24#issuecomment-623784329)

**Comment by xiaomage-devops** [comment]
@devstein yes, i setup the gpg according to the above example, but still have the issue. It is very strange, everything works fine on local env(mac), but do not  work fine on Argocd. I really do not understand what the error means.

**Comment by majinghe** [comment]
@devstein  Any good suggestion for this?

**Comment by devstein** [comment]
@majinghe From the [SOPS code](https://github.com/mozilla/sops/blob/master/usererrors.go#L38-L42), you can see the error is a failure to find the decryption key, so its definitely a configuration issue. Would you mind sharing the rendered `argocd-repo-server` Deployment manifest? Without seeing it, I don't have any direct suggestions

**Comment by majinghe** [comment]
@devstein  Sure
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
  namespace: argocd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname
            weight: 5
      automountServiceAccountToken: false
      containers:
      - command:
        - uid_entrypoint.sh
        - argocd-repo-server
        - --redis
        - argocd-redis:6379
        env:
        - name: XDG_CONFIG_HOME
          value: /.config
        - name: GNUPGHOME
          value: /home/argocd/.gnupg
        image: argoproj/argocd:v1.8.1
        imagePullPolicy: Always
        name: argocd-repo-server
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8084
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8081
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config/ssh
          name: ssh-known-hosts
        - mountPath: /app/config/tls
          name: tls-certs
        - mountPath: /app/config/gpg/source
          name: gpg-keys
        - mountPath: /app/config/gpg/keys
          name: gpg-keyring
        - mountPath: /home/argocd/.gnupg
          name: gnupg-home
          subPath: .gnupg
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
          name: custom-tools
          subPath: ksops.so
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - echo "Installing KSOPS..."; export PKG_NAME=ksops; mv ${PKG_NAME}.so /custom-tools/;
          mv $GOPATH/bin/kustomize /custom-tools/; echo "Done.";
        command:
        - /bin/sh
        - -c
        image: viaductoss/ksops:v2.3.2
        imagePullPolicy: IfNotPresent
        name: install-ksops
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      - command:
        - gpg
        - --import
        - /deploy-pgp-key/deploy-key.asc
        env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
        image: argoproj/argocd:v1.8.1
        imagePullPolicy: IfNotPresent
        name: import-gpg-key
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /deploy-pgp-key
          name: deploy-pgp-key
        - mountPath: /gnupg-home
          name: gnupg-home
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: argocd-ssh-known-hosts-cm
        name: ssh-known-hosts
      - configMap:
          defaultMode: 420
          name: argocd-tls-certs-cm
        name: tls-certs
      - configMap:
          defaultMode: 420
          name: argocd-gpg-keys-cm
        name: gpg-keys
      - emptyDir: {}
        name: gpg-keyring
      - emptyDir: {}
        name: custom-tools
      - emptyDir: {}
        name: gnupg-home
      - name: deploy-pgp-key
        secret:
          defaultMode: 420
          secretName: deploy-pgp-key
```
